{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "chart.fullname" $ }}-ingress
  labels:
    app: {{ $.Values.appName }}
  annotations:
    {{- if $.Values.ingress.tls.enabled }}
    ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: {{ $.Values.ingress.issuer }}
    {{- end }}
    {{- range $key, $value := $.Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
{{- range .Values.ingress.hosts }}  
  - host: {{ .name }}
    http:
      paths:
      - path: {{ $.Values.ingress.path }}
        backend:
          service:
            name: {{ template "chart.fullname" $ }}
            port:
              number: {{ $.Values.service.port }}
        pathType: ImplementationSpecific
{{- end }}      
  {{- if $.Values.ingress.tls.enabled }}
  tls:
{{- range .Values.ingress.hosts }}   
  - hosts:
    - {{ .name }}
    secretName: {{ .secretname }}
  {{- end }}
{{- end }}
---
{{- end }}

