apiVersion: v1
kind: Service
metadata:
  name: {{ template "chart.fullname" . }}-service
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.service.port }}  
    protocol: {{ .Values.service.protocol }} 
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }} 
